"""add sync_log table

Revision ID: 2594b1dc0e2e
Revises: 3342af4e19d8
Create Date: 2026-09-22 17:53:39.328468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2594b1dc0e2e'
down_revision = '3342af4e19d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_log_sync_type'), ['sync_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_log_synced_at'), ['synced_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_log_synced_at'))
        batch_op.drop_index(batch_op.f('ix_sync_log_sync_type'))

    op.drop_table('sync_log')
    # ### end Alembic commands ###
