"""add currency_rates table

Revision ID: 985c0e5e9a64
Revises: f04bb4b52337
Create Date: 2026-09-19 10:10:43.254532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985c0e5e9a64'
down_revision = 'f04bb4b52337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('rate_rub', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'rate_date', name='uq_currency_rate_code_date')
    )
    with op.batch_alter_table('currency_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_rates_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_rates_rate_date'), ['rate_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_currency_rates_code'))

    op.drop_table('currency_rates')
    # ### end Alembic commands ###
