"""add event_log table

Revision ID: f04bb4b52337
Revises: 01dc2cdf7dfd
Create Date: 2026-09-17 13:42:17.986274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04bb4b52337'
down_revision = '01dc2cdf7dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_status'), ['status'], unique=False)
        batch_op.create_index('ix_event_log_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index('ix_event_log_status_created')
        batch_op.drop_index(batch_op.f('ix_event_log_status'))
        batch_op.drop_index(batch_op.f('ix_event_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_log_created_at'))

    op.drop_table('event_log')
    # ### end Alembic commands ###
